#!/bin/bash

# This builds a very minimal barbican container images with the configurations
# that are available in this repository. The image itself is based on the one
# generated by kolla

docker build --tag barbican-minimal:latest .
